Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 146, in <module>
    train_dataloader, test_dataloader = create_FashionMNIST_data_loaders()
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/data_process.py", line 104, in create_FashionMNIST_data_loaders
    plot_img(train_dataset)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 68, in plot_img
    plt.imshow(tensor[0][random.randint(0, len(tensor))].permute(1, 2, 0))
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 146, in <module>
    train_dataloader, test_dataloader = create_FashionMNIST_data_loaders()
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/data_process.py", line 104, in create_FashionMNIST_data_loaders
    plot_img(train_dataset)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 68, in plot_img
    plt.imshow(tensor[0][random.randint(0, len(tensor))].permute(1, 2, 0))
IndexError: tuple index out of range
Image size: <built-in method size of Tensor object at 0x790d74df9760>