Dataset: ./data/cats_dogs_full/train and ./data/cats_dogs_full/test
Train dataloader: 624 batches
Test dataloader: 157 batches
--------Epoch: 0
-Training...
Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 142, in <module>
    train_loss, train_acc = train_model(model, train_dataloader, loss_fn, optimizer)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 59, in train_model
    train_acc += accuracy_fn(y, train_pred)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 21, in accuracy_fn
    correct = torch.eq(y_true, y_pred).sum().item()
RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 1
Traceback (most recent call last):
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 142, in <module>
    train_loss, train_acc = train_model(model, train_dataloader, loss_fn, optimizer)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/CNN.py", line 59, in train_model
    train_acc += accuracy_fn(y, train_pred)
  File "/home/danielcarias/Documents/Estudo NN/Estudo/CNN/first_project/utils.py", line 21, in accuracy_fn
    correct = torch.eq(y_true, y_pred).sum().item()
RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 1